#!/usr/bin/env python3
"""
OfferWise Test Corpus Generator
================================
Generates a static set of test PDFs that mirror real-world documents
homebuyers upload to OfferWise. Run once to populate test_corpus/.

Real-world patterns this corpus covers:
  1. Digital PDFs from DocuSign / SkySlope / zipForms (clean text extraction)
  2. Scanned paper forms with handwriting (OCR required)
  3. Phone photos saved as PDF (bad quality, shadows, angles)
  4. Faded photocopies (low contrast)
  5. Crooked/rotated scans
  6. Mixed digital cover + scanned disclosure pages
  7. Inspection reports with embedded damage photos
  8. Multi-page realistic inspection reports (15+ pages)
  9. Adversarial: blank PDFs, wrong doc types, metadata-only, corrupted
  10. Edge cases: huge text walls, tiny 1-page summaries, redacted sections

Usage:
    python generate_test_corpus.py
    # Creates/refreshes test_corpus/ directory

Dependencies (test-only):
    pip install fpdf2 Pillow PyPDF2
"""

import os
import sys
import random
import tempfile
import warnings
from datetime import datetime, timedelta
from io import BytesIO

# Suppress fpdf2 deprecation warnings about ln= parameter
warnings.filterwarnings('ignore', category=DeprecationWarning, module='fpdf')

# ---------------------------------------------------------------------------
# Dependencies check
# ---------------------------------------------------------------------------
try:
    from fpdf import FPDF
except ImportError:
    print("ERROR: fpdf2 required. Install with: pip install fpdf2")
    sys.exit(1)

try:
    from PIL import Image, ImageDraw, ImageFont, ImageFilter
    PILLOW_AVAILABLE = True
except ImportError:
    PILLOW_AVAILABLE = False
    print("WARNING: Pillow not available. Scanned/image-based PDFs will be skipped.")

try:
    import PyPDF2
    PYPDF2_AVAILABLE = True
except ImportError:
    PYPDF2_AVAILABLE = False
    print("WARNING: PyPDF2 not available. Mixed PDF will be skipped.")


CORPUS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'test_corpus')
os.makedirs(CORPUS_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# Font helper
# ---------------------------------------------------------------------------
def _get_font(size=14, style='regular'):
    """Get a system font, preferring fonts that look realistic."""
    font_map = {
        'regular': [
            '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf',
            '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf',
            '/usr/share/fonts/truetype/crosextra/Caladea-Regular.ttf',
        ],
        'bold': [
            '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf',
            '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf',
            '/usr/share/fonts/truetype/crosextra/Caladea-Bold.ttf',
        ],
        'italic': [
            '/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf',
            '/usr/share/fonts/truetype/crosextra/Caladea-Italic.ttf',
            '/usr/share/fonts/truetype/crosextra/Carlito-Italic.ttf',
        ],
        'handwritten': [
            '/usr/share/fonts/truetype/crosextra/Carlito-Italic.ttf',
            '/usr/share/fonts/truetype/crosextra/Caladea-Italic.ttf',
        ],
    }
    for fp in font_map.get(style, font_map['regular']):
        if os.path.exists(fp):
            return ImageFont.truetype(fp, size)
    return ImageFont.load_default()


def _img_to_pdf(images, quality=70):
    """Convert list of PIL images to a single PDF."""
    pdf = FPDF()
    tmp_files = []
    for img in images:
        pdf.add_page()
        tmp = tempfile.NamedTemporaryFile(suffix='.jpg', delete=False)
        img.save(tmp, format='JPEG', quality=quality)
        tmp.close()
        tmp_files.append(tmp.name)
        pdf.image(tmp.name, 0, 0, 210, 297)
    out = pdf.output()
    for f in tmp_files:
        try:
            os.unlink(f)
        except Exception:
            pass
    return out


def save_pdf(filename, pdf_bytes):
    """Save PDF bytes to corpus directory."""
    path = os.path.join(CORPUS_DIR, filename)
    with open(path, 'wb') as f:
        f.write(pdf_bytes)
    size_kb = len(pdf_bytes) / 1024
    print(f"  ✅ {filename} ({size_kb:.0f} KB)")


# ===========================================================================
# 1. CLEAN DIGITAL TDS (DocuSign / zipForms style)
# ===========================================================================
def gen_digital_tds_clean():
    """Realistic 4-page digital TDS as generated by DocuSign/zipForms.
    This is the most common document type — ~60% of uploads."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Page 1: Header + Section A (Items)
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 8, 'REAL ESTATE TRANSFER DISCLOSURE STATEMENT', ln=True, align='C')
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(0, 5, '(California Civil Code Section 1102 et seq.)', ln=True, align='C')
    pdf.cell(0, 5, 'THIS STATEMENT IS A DISCLOSURE OF THE CONDITION OF THE ABOVE DESCRIBED PROPERTY IN COMPLIANCE', ln=True, align='C')
    pdf.cell(0, 5, 'WITH SECTION 1102 OF THE CIVIL CODE AS OF THE DATE SIGNED BY THE TRANSFEROR.', ln=True, align='C')
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'Property Address: 2847 Winfield Blvd, San Jose, CA 95128', ln=True)
    pdf.cell(0, 6, 'City: San Jose    County: Santa Clara    Zip: 95128', ln=True)
    pdf.ln(4)

    # Section A
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 7, 'I. COORDINATION WITH OTHER DISCLOSURE FORMS', ln=True)
    pdf.set_font('Helvetica', '', 9)
    pdf.multi_cell(0, 5, 'This Real Property Transfer Disclosure Statement is made pursuant to Section 1102 of the Civil Code. '
                   'Other statutes require disclosures, depending upon the details of the particular real estate transaction.')
    pdf.ln(3)

    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 7, 'II. SELLER\'S INFORMATION', ln=True)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'A. The subject property has the following items:', ln=True)
    pdf.set_font('Helvetica', '', 9)

    items = [
        ('Range/Oven', True), ('Dishwasher', True), ('Garbage Disposal', True),
        ('Washer/Dryer Hookups', True), ('Rain Gutters', True), ('Burglar Alarm', False),
        ('Smoke Detector(s)', True), ('Fire Alarm', True), ('Carbon Monoxide Device(s)', True),
        ('TV Antenna', False), ('Satellite Dish', False), ('Intercom', False),
        ('Central Heating', True), ('Central Air Conditioning', True), ('Evaporator Cooler(s)', False),
        ('Wall/Window Air Conditioning', False), ('Fireplace(s)', True), ('Gas Starter', True),
        ('Garage: Attached', True), ('Garage: Door Opener(s)', True), ('Number Remote Controls: 2', True),
        ('Pool', False), ('Spa/Hot Tub', False), ('Child Resistant Barrier for Pool', False),
        ('Patio/Decking', True), ('Built-in Barbecue', False), ('Solar Panels (owned)', False),
        ('Water Heater: Gas', True), ('Water Softener (owned)', False), ('Security Gate(s)', False),
        ('Automatic Garage Door Opener(s)', True), ('Sump Pump', False), ('220 Volt Wiring in Garage', True),
    ]

    for item, checked in items:
        mark = '[X]' if checked else '[ ]'
        text = f'{mark} {item}'
        pdf.cell(63, 5, text[:30])
        if pdf.get_x() > 155:
            pdf.ln()
    pdf.ln()
    pdf.set_x(10)  # Reset to left margin

    pdf.ln(5)
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(0, 5, 'Exhaust Fan(s) in: [X] Kitchen [X] Bathroom(s)', ln=True)
    pdf.cell(0, 5, 'Gas Supply: [X] Utility  Electricity: [X] Utility  Water: [X] City', ln=True)
    pdf.cell(0, 5, 'Sewer: [X] City  Window Screens: [X] Full  Roof Type: Composition Shingle, Age: ~18 yrs', ln=True)

    # Page 2: Section B (Defects)
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, 'B. Are you (Seller) aware of any significant defects/malfunctions in any of the following?', ln=True)
    pdf.set_font('Helvetica', '', 9)

    defect_categories = [
        ('Interior Walls', 'Yes', 'Minor cracks in living room wall near window. Cosmetic only.'),
        ('Ceilings', 'No', ''),
        ('Floors', 'No', ''),
        ('Exterior Walls', 'No', ''),
        ('Insulation', 'No', ''),
        ('Roof(s)', 'Yes', 'Composition shingle, 18 years old. Some granule loss noted. No leaks observed.'),
        ('Windows', 'No', ''),
        ('Doors', 'No', ''),
        ('Foundation', 'No', ''),
        ('Slab(s)', 'No', ''),
        ('Driveways', 'Yes', 'Hairline crack in driveway near garage. Does not affect use.'),
        ('Sidewalks', 'No', ''),
        ('Walls/Fences', 'No', ''),
        ('Electrical Systems', 'No', ''),
        ('Plumbing/Sewers/Septics', 'No', ''),
        ('Other Structural Components', 'No', ''),
    ]

    for category, answer, detail in defect_categories:
        yes_mark = '(X)' if answer == 'Yes' else '( )'
        no_mark = '(X)' if answer == 'No' else '( )'
        pdf.cell(0, 5, f'{category}: Yes {yes_mark}  No {no_mark}', ln=True)
        if detail:
            pdf.set_font('Helvetica', 'I', 8)
            pdf.cell(0, 4, f'   Detail: {detail}', ln=True)
            pdf.set_font('Helvetica', '', 9)

    pdf.ln(3)
    pdf.cell(0, 5, 'Additional Seller disclosures:', ln=True)
    pdf.set_font('Helvetica', '', 8)
    pdf.multi_cell(0, 4, 'Roof was patched in 2021 after winter storm. Patch was done by licensed contractor (receipt available). '
                   'HVAC unit serviced annually - last service August 2024. Water heater replaced in 2020 (50 gallon, gas). '
                   'Garage door opener replaced in 2022. Kitchen remodeled in 2019 with permits pulled from City of San Jose. '
                   'Bathroom updated in 2021 - no permits were pulled for cosmetic updates only (tile, fixtures, vanity).')

    # Page 3: Section C (Awareness)
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, 'C. Are you (Seller) aware of any of the following:', ln=True)
    pdf.set_font('Helvetica', '', 9)

    awareness_items = [
        ('Substances, materials, or products which may be an environmental hazard such as, but not limited to, '
         'asbestos, formaldehyde, radon gas, lead-based paint, mold, fuel or chemical storage tanks', 'No'),
        ('Features of the property shared in common with adjoining landowners, such as walls, fences, and driveways, '
         'whose use or responsibility for maintenance may have an effect on the subject property', 'No'),
        ('Any encroachments, easements or similar matters that may affect your interest in the subject property', 'No'),
        ('Room additions, structural modifications, or other alterations or repairs made without necessary permits', 'Yes'),
        ('Room additions, structural modifications, or other alterations or repairs not in compliance with building codes', 'No'),
        ('Fill (compacted or otherwise) on the property or any portion thereof', 'No'),
        ('Any settling from any cause, or slippage, sliding, or other soil problems', 'No'),
        ('Flooding, drainage or grading problems', 'No'),
        ('Major damage to the property or any of the structures from fire, earthquake, floods, or landslides', 'No'),
        ('Any zoning violations, nonconforming uses, violations of "setback" requirements', 'No'),
        ('Neighborhood noise problems or other nuisances', 'Yes'),
        ('CC&Rs or other deed restrictions or obligations', 'No'),
        ('Homeowners\' Association which has any authority over the subject property', 'No'),
        ('Any "common areas" (facilities such as pools, tennis courts, walkways, or similar)', 'No'),
        ('Any notices of abatement or citations against the property', 'No'),
        ('Any lawsuits by or against the seller threatening to or affecting this real property', 'No'),
    ]

    for i, (question, answer) in enumerate(awareness_items, 1):
        pdf.set_x(10)
        pdf.set_font('Helvetica', '', 8)
        yes_mark = '(X)' if answer == 'Yes' else '( )'
        no_mark = '(X)' if answer == 'No' else '( )'
        pdf.multi_cell(0, 4, f'{i}. {question}')
        pdf.set_x(10)
        pdf.cell(0, 4, f'   Yes {yes_mark}  No {no_mark}', new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

    # Detail for "Yes" answers
    pdf.ln(2)
    pdf.set_x(10)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.multi_cell(0, 4, 'Item 4 detail: Bathroom update in 2021 was cosmetic only (tile, fixtures, vanity) - no structural changes, '
                   'no permits required per City of San Jose guidelines for cosmetic-only work.')
    pdf.set_x(10)
    pdf.multi_cell(0, 4, 'Item 11 detail: Occasional airplane noise from San Jose International Airport. Flight path is north of property. '
                   'Most noticeable early morning (6-7 AM) and evening (9-10 PM).')

    # Page 4: Section D + Signatures
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, 'D. ADDITIONAL SELLER DISCLOSURES:', ln=True)
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(0, 5, '1. [X] Smoke Detector(s) installed per Health and Safety Code Section 13113.8', ln=True)
    pdf.cell(0, 5, '2. [X] Water Heater braced, anchored, or strapped in compliance with Section 19211', ln=True)
    pdf.cell(0, 5, '3. [X] Carbon Monoxide device(s) installed per Health and Safety Code Section 17926', ln=True)
    pdf.ln(5)

    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, 'III. AGENT VISUAL INSPECTION DISCLOSURE', ln=True)
    pdf.set_font('Helvetica', '', 8)
    pdf.multi_cell(0, 4, 'The undersigned, based on a reasonably competent and diligent visual inspection of the accessible areas '
                   'of the property, states the following: Property appears to be in good overall condition for its age. '
                   'Roof shows age-appropriate wear. Driveway has cosmetic crack. No evidence of water intrusion observed. '
                   'Recommend buyer obtain professional inspections for roof, foundation, and pest.')
    pdf.ln(10)

    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(0, 6, 'Seller(s): Michael Chen & Jennifer Chen', ln=True)
    pdf.cell(0, 6, f'Date: {(datetime.now() - timedelta(days=30)).strftime("%m/%d/%Y")}', ln=True)
    pdf.ln(3)
    pdf.cell(0, 6, 'Seller\'s Agent: Lisa Nakamura, Coldwell Banker Realty', ln=True)
    pdf.cell(0, 6, f'Date: {(datetime.now() - timedelta(days=30)).strftime("%m/%d/%Y")}', ln=True)
    pdf.ln(3)
    pdf.cell(0, 6, 'Buyer\'s Agent: ____________________', ln=True)
    pdf.cell(0, 6, 'Date: ____________________', ln=True)
    pdf.ln(5)

    pdf.set_font('Helvetica', '', 7)
    pdf.cell(0, 4, 'Docusign Envelope ID: A4F3B7C2-8D91-4E56-B2A1-7C3D9F8E5A12', ln=True)
    pdf.cell(0, 4, f'Generated by zipForms Edition  {datetime.now().strftime("%m/%d/%Y %I:%M %p")} Pacific', ln=True)

    save_pdf('01_digital_tds_clean.pdf', pdf.output())


# ===========================================================================
# 2. CLEAN DIGITAL INSPECTION REPORT (15 pages, realistic detail)
# ===========================================================================
def gen_digital_inspection_clean():
    """Realistic multi-page digital inspection report from inspection software.
    Mirrors reports from HomeGauge, Spectora, or InspectIt."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Cover page
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 22)
    pdf.ln(30)
    pdf.cell(0, 12, 'HOME INSPECTION REPORT', ln=True, align='C')
    pdf.ln(8)
    pdf.set_font('Helvetica', '', 12)
    pdf.cell(0, 8, 'Property: 2847 Winfield Blvd, San Jose, CA 95128', ln=True, align='C')
    pdf.cell(0, 8, f'Inspection Date: {(datetime.now() - timedelta(days=14)).strftime("%B %d, %Y")}', ln=True, align='C')
    pdf.cell(0, 8, 'Report #: INS-2025-04281', ln=True, align='C')
    pdf.ln(10)
    pdf.cell(0, 8, 'Prepared for: David & Maria Santos', ln=True, align='C')
    pdf.cell(0, 8, 'Prepared by: Robert Anderson, ASHI Certified Inspector #247891', ln=True, align='C')
    pdf.cell(0, 8, 'Anderson Home Inspections, LLC', ln=True, align='C')
    pdf.cell(0, 8, 'License #HI-2019-04872  |  (408) 555-0147', ln=True, align='C')
    pdf.ln(20)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.multi_cell(0, 5, 'NOTICE: This report is the exclusive property of Anderson Home Inspections, LLC and the client(s) '
                   'named above. Use by any unauthorized persons is prohibited. This inspection was performed in accordance '
                   'with the Standards of Practice of the American Society of Home Inspectors (ASHI).')

    # Executive Summary
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 8, 'EXECUTIVE SUMMARY', ln=True)
    pdf.set_font('Helvetica', '', 9)
    pdf.ln(3)
    pdf.multi_cell(0, 5, 'This single-family residence was built in 2006 and contains approximately 1,847 square feet of living '
                   'space. The property features 3 bedrooms, 2.5 bathrooms, an attached 2-car garage, and a landscaped rear yard. '
                   'The home is served by city water and sewer, natural gas, and 200 amp electrical service.')
    pdf.ln(3)

    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'SUMMARY OF SIGNIFICANT FINDINGS:', ln=True)
    pdf.set_font('Helvetica', '', 9)

    findings_summary = [
        ('SAFETY', 'Exposed wiring junction box in garage lacks cover plate. Repair immediately.'),
        ('SAFETY', 'Absence of GFCI protection at two exterior outlets. Upgrade recommended.'),
        ('MAJOR', 'Roof composition shingles show significant granule loss and curling on south-facing slope. '
         'Estimated remaining life 2-4 years. Budget for replacement ($12,000-$18,000).'),
        ('MAJOR', 'Evidence of past moisture intrusion at master bedroom ceiling. Stain is dry and appears '
         'inactive but source should be confirmed. Possible flashing or roof-related.'),
        ('MAJOR', 'HVAC condenser unit (18 years old) showing corrosion on condenser coils. '
         'Functional but nearing end of useful life. Budget for replacement ($4,000-$7,000).'),
        ('MODERATE', 'Hairline crack in foundation east wall, approximately 3 feet horizontal. '
         'Appears cosmetic/settling. Monitor for changes. If crack widens, consult structural engineer.'),
        ('MODERATE', 'Two garage outlets tested open ground. Repair needed for safety.'),
        ('MODERATE', 'Kitchen faucet has slow drip. Washer replacement needed (~$150).'),
        ('MINOR', 'Driveway hairline crack near garage apron. Seal to prevent water infiltration.'),
        ('MINOR', 'Caulking deteriorated at multiple window frames. Recaulk for weatherproofing.'),
        ('MINOR', 'Fence post at rear property line shows wood rot at base. Replace before failure.'),
    ]

    for severity, desc in findings_summary:
        color = {'SAFETY': 'RED', 'MAJOR': 'ORANGE', 'MODERATE': 'YELLOW', 'MINOR': 'BLUE'}
        pdf.set_font('Helvetica', 'B', 9)
        pdf.cell(22, 5, f'[{severity}]', ln=False)
        pdf.set_font('Helvetica', '', 9)
        pdf.multi_cell(0, 5, desc)
        pdf.ln(1)

    # Detailed sections
    sections = [
        ('ROOFING', [
            ('Type', 'Composition shingle (architectural)'),
            ('Age', 'Approximately 18 years (original to construction)'),
            ('Condition', 'DEFICIENT - Significant granule loss observed on south-facing slope. '
             'Multiple areas of curling and lifting shingles. Ridge cap appears intact. '
             'Flashing at chimney and vent pipes shows minor deterioration. '
             'Gutters and downspouts functional with minor debris accumulation.'),
            ('Estimated Remaining Life', '2-4 years'),
            ('Estimated Replacement Cost', '$12,000-$18,000 for complete re-roof'),
            ('Recommendation', 'Obtain quotes from licensed roofing contractors. Plan for replacement within 2-3 years. '
             'Monitor for any active leaks, especially at flashing points.'),
        ]),
        ('EXTERIOR', [
            ('Siding', 'Fiber cement (HardiePlank). Good condition overall. Minor paint touch-up needed at north wall.'),
            ('Trim', 'Wood trim at eaves. No visible rot or damage.'),
            ('Windows', 'Dual-pane vinyl. Functional. Caulking deteriorated at 4 window frames - recaulk recommended.'),
            ('Doors', 'Front entry: fiberglass, good condition. Sliding glass: aluminum frame, tracks need cleaning, '
             'rollers functional.'),
            ('Driveway', 'Concrete. Hairline crack near garage apron (~4 feet long). Cosmetic. Seal to prevent water infiltration.'),
            ('Walkways', 'Concrete front walkway. Good condition, no trip hazards.'),
            ('Fence', 'Wood privacy fence. Generally good. One post at rear shows wood rot at base - replace.'),
            ('Grading/Drainage', 'Positive grade away from foundation on 3 sides. East side appears level - monitor during rain.'),
        ]),
        ('FOUNDATION/STRUCTURE', [
            ('Type', 'Concrete perimeter foundation with slab-on-grade'),
            ('Condition', 'MARGINAL - Hairline horizontal crack on east wall exterior, approximately 3 feet long. '
             'Crack width is less than 1/8 inch and appears consistent with normal settling. '
             'No displacement or vertical offset observed. Interior inspection shows no corresponding cracks.'),
            ('Crawl Space', 'N/A - slab-on-grade construction'),
            ('Recommendation', 'Monitor crack width seasonally. Mark endpoints with pencil and date. '
             'If crack widens beyond 1/4 inch or shows vertical displacement, consult a licensed structural engineer. '
             'Estimated cost for engineer evaluation: $400-$600.'),
        ]),
        ('ELECTRICAL', [
            ('Panel', '200 amp main panel in garage. Square D brand. All breakers labeled. No double-tapped breakers.'),
            ('Wiring Type', 'Copper throughout (Romex NM-B). Appropriate for 2006 construction.'),
            ('Outlets/Switches', 'Tested representative sampling. Two garage outlets showed open ground - repair needed. '
             'All GFCI outlets in kitchen and bathrooms tested and functioning.'),
            ('Deficiency', 'SAFETY: Exposed junction box in garage ceiling lacks cover plate. Must be repaired immediately. '
             'Estimated cost: $50-$100.'),
            ('Deficiency', 'SAFETY: Two exterior outlets lack GFCI protection. Current code requires GFCI for all exterior outlets. '
             'Estimated cost: $150-$300 for electrician upgrade.'),
        ]),
        ('PLUMBING', [
            ('Supply Lines', 'Copper main. PEX distribution (typical for 2006 construction). Good condition.'),
            ('Drain Lines', 'ABS drain/waste/vent. Functional. All drains tested, no slow drains detected.'),
            ('Water Heater', 'AO Smith 50-gallon gas water heater. Installed 2020 (sticker confirms). '
             'Properly strapped per CA requirements. T&P valve present and discharge pipe properly routed.'),
            ('Fixtures', 'Kitchen faucet: Slow drip from spout when off. Likely needs washer replacement ($100-$150). '
             'All other fixtures functional with adequate flow and drainage.'),
            ('Hose Bibs', 'Two exterior hose bibs tested. Functional, no visible leaks.'),
        ]),
        ('HVAC', [
            ('Heating', 'Lennox forced-air gas furnace. Approximately 18 years old (original). '
             'Functional at time of inspection. Filter was dirty - recommend replacement.'),
            ('Cooling', 'Lennox split system A/C. Condenser unit 18 years old. Condenser coils show corrosion. '
             'Unit produced 17°F temperature differential at registers (acceptable range: 15-20°F). '
             'Functional but nearing end of useful life.'),
            ('Estimated Remaining Life', '2-5 years for both furnace and condenser'),
            ('Estimated Replacement Cost', '$4,000-$7,000 for A/C condenser; $3,000-$5,000 for furnace; '
             '$7,000-$11,000 for complete system replacement'),
            ('Ductwork', 'Flex duct in attic. Connections appear secure. Minor compression at one run - '
             'may reduce airflow to master bedroom.'),
            ('Thermostat', 'Nest programmable thermostat. Functional.'),
        ]),
        ('INTERIOR', [
            ('Walls/Ceilings', 'Generally good condition. Minor cracks in living room wall near window (cosmetic/settling). '
             'Water stain on master bedroom ceiling approximately 2 feet in diameter. Stain appears dry and inactive. '
             'No moisture detected with meter at time of inspection. Source should be confirmed - may be related to '
             'roof flashing deterioration noted above.'),
            ('Floors', 'Hardwood in living areas (good condition). Tile in bathrooms and kitchen (good condition). '
             'Carpet in bedrooms (fair condition, normal wear).'),
            ('Kitchen', 'Appliances tested: Range, oven, dishwasher, garbage disposal, microwave - all functional. '
             'Countertops: granite, good condition. Cabinets: wood, good condition, soft-close hinges.'),
            ('Bathrooms', 'Master bath: Tile shower, no visible grout issues. Exhaust fan functional. '
             'Hall bath: Tub/shower combo. Functional. Caulk at tub/tile junction needs refreshing.'),
        ]),
        ('ATTIC', [
            ('Access', 'Pull-down stair in hallway. Attic accessed and inspected.'),
            ('Insulation', 'Blown fiberglass, approximately R-30 (adequate for CA Zone 4).'),
            ('Ventilation', 'Ridge vent and soffit vents. Appears adequate.'),
            ('Observations', 'No visible signs of active leaks, rodent activity, or mold. '
             'Roof decking appears dry and sound from interior.'),
        ]),
        ('GARAGE', [
            ('Type', 'Attached 2-car garage with automatic door openers (2 remotes)'),
            ('Condition', 'Good overall. Auto-reverse on door openers tested and functional.'),
            ('Fire Separation', 'Fire-rated drywall appears intact between garage and living space. '
             'Self-closing door to house present and functional.'),
            ('Deficiency', 'Junction box on ceiling missing cover plate (SAFETY - noted above). '
             'Two outlets open ground (noted in Electrical section).'),
        ]),
    ]

    for section_name, items in sections:
        pdf.add_page()
        pdf.set_font('Helvetica', 'B', 13)
        pdf.cell(0, 8, section_name, ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        for label, value in items:
            pdf.set_font('Helvetica', 'B', 9)
            pdf.cell(40, 5, f'{label}:', ln=False)
            pdf.set_font('Helvetica', '', 9)
            pdf.multi_cell(0, 5, value)
            pdf.ln(1)

    # Final page: disclaimers
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'LIMITATIONS AND DISCLAIMERS', ln=True)
    pdf.set_font('Helvetica', '', 8)
    pdf.multi_cell(0, 4,
        'This inspection is a visual examination of the readily accessible areas of the property at the time of '
        'the inspection. The inspection is not technically exhaustive. Areas that were inaccessible, concealed, or '
        'obstructed were not inspected. This report does not include inspection of: swimming pools/spas, outbuildings, '
        'underground systems, environmental hazards (asbestos, lead, mold, radon), pest/wood-destroying organisms, '
        'or geological conditions.\n\n'
        'Estimated repair costs are provided as general guidance only and are based on typical contractor pricing in '
        'the San Jose, CA metropolitan area as of the inspection date. Actual costs may vary. Obtain professional '
        'estimates before making purchasing decisions.\n\n'
        'This report is not a guarantee or warranty, expressed or implied, regarding the condition of the property. '
        'The inspector assumes no liability for conditions that develop after the inspection date.')

    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(0, 6, f'Inspector: Robert Anderson, ASHI #247891', ln=True)
    pdf.cell(0, 6, f'Date: {(datetime.now() - timedelta(days=14)).strftime("%m/%d/%Y")}', ln=True)
    pdf.cell(0, 6, 'Anderson Home Inspections, LLC', ln=True)

    save_pdf('02_digital_inspection_clean.pdf', pdf.output())


# ===========================================================================
# 3. NIGHTMARE SCENARIO - SELLER HIDING MAJOR ISSUES
# ===========================================================================
def gen_digital_tds_nightmare():
    """TDS where seller checks 'No' to everything despite known major issues.
    This is what OfferWise is designed to catch — contradictions between disclosure and inspection."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 8, 'REAL ESTATE TRANSFER DISCLOSURE STATEMENT', ln=True, align='C')
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(0, 5, '(California Civil Code Section 1102 et seq.)', ln=True, align='C')
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'Property Address: 456 Hidden Problem Way, Sunnyvale, CA 94086', ln=True)
    pdf.ln(3)

    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'B. Are you (Seller) aware of any significant defects/malfunctions?', ln=True)
    pdf.set_font('Helvetica', '', 9)

    # Seller says "No" to EVERYTHING
    for cat in ['Interior Walls', 'Ceilings', 'Floors', 'Exterior Walls', 'Insulation',
                'Roof(s)', 'Windows', 'Doors', 'Foundation', 'Slab(s)', 'Driveways',
                'Sidewalks', 'Walls/Fences', 'Electrical Systems', 'Plumbing/Sewers/Septics',
                'Other Structural Components']:
        pdf.cell(0, 5, f'{cat}: Yes ( )  No (X)', ln=True)

    pdf.ln(3)
    pdf.cell(0, 5, 'Additional disclosures: Property is being sold in its current condition.', ln=True)
    pdf.cell(0, 5, 'No material defects known to seller.', ln=True)

    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'C. Awareness Questions:', ln=True)
    pdf.set_font('Helvetica', '', 9)
    for q in ['Environmental hazards', 'Encroachments/easements', 'Room additions without permits',
              'Settling/soil problems', 'Flooding/drainage', 'Major damage (fire/earthquake/flood)',
              'Zoning violations', 'Neighborhood noise/nuisances', 'CC&Rs', 'HOA',
              'Lawsuits', 'Abatement/citations']:
        pdf.cell(0, 5, f'{q}: Yes ( )  No (X)', ln=True)

    pdf.ln(3)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(0, 6, f'Seller: Robert & Sarah Williams', ln=True)
    pdf.cell(0, 6, f'Date: {(datetime.now() - timedelta(days=45)).strftime("%m/%d/%Y")}', ln=True)

    save_pdf('03_digital_tds_nightmare_no_disclosure.pdf', pdf.output())


def gen_digital_inspection_nightmare():
    """Inspection report with critical findings that directly contradict the clean TDS above."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 16)
    pdf.cell(0, 10, 'HOME INSPECTION REPORT', ln=True, align='C')
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 7, 'Property: 456 Hidden Problem Way, Sunnyvale, CA 94086', ln=True, align='C')
    pdf.cell(0, 7, f'Date: {(datetime.now() - timedelta(days=10)).strftime("%B %d, %Y")}', ln=True, align='C')
    pdf.cell(0, 7, 'Inspector: Patricia Nguyen, ASHI #189234', ln=True, align='C')
    pdf.ln(5)

    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'CRITICAL FINDINGS SUMMARY', ln=True)
    pdf.set_font('Helvetica', '', 9)

    critical_findings = [
        ('CRITICAL - FOUNDATION', 'Significant structural cracking in foundation. Multiple cracks exceeding 1/4 inch width '
         'with vertical displacement observed on east and south walls. Step-cracking pattern suggests differential settling. '
         'THIS IS A SAFETY CONCERN. Immediate evaluation by licensed structural engineer required. '
         'Estimated repair: $15,000-$45,000 depending on remediation method (pier/beam, mudjacking, or complete section replacement). '
         'NOTE: This type of cracking typically develops over years and would be visible to property occupants.'),

        ('CRITICAL - ROOF', 'Active water intrusion detected in three locations. Roof is well past useful life with '
         'extensive damage: missing shingles across south and west slopes, deteriorated flashing at all penetrations, '
         'visible daylight through roof decking in attic at two locations. Active leak staining on attic insulation '
         'and ceiling drywall in master bedroom and hallway. Mold growth observed on attic decking in two areas (~3 sq ft total). '
         'Full roof replacement required immediately. Estimated cost: $18,000-$25,000. '
         'Mold remediation estimated: $3,000-$8,000. '
         'NOTE: Multiple layers of roofing material suggest previous repairs/patches without addressing underlying issues.'),

        ('CRITICAL - ELECTRICAL', 'Federal Pacific Stab-Lok electrical panel identified. This panel type has a documented '
         'history of breaker failure and fire risk. Panel does not reliably trip under overload conditions. '
         'Multiple insurance companies will not insure homes with this panel. Immediate replacement required. '
         'Additionally: Knob-and-tube wiring discovered in attic section, suggesting unpermitted addition. '
         'Estimated panel replacement: $2,500-$4,000. Wiring remediation: $5,000-$12,000. '
         'NOTE: Federal Pacific panels were common in 1960s-1980s construction but this home is listed as built 2002 - '
         'suggesting the garage conversion/addition used the original panel from a prior structure.'),

        ('MAJOR - PLUMBING', 'Main sewer line shows signs of root intrusion. Camera inspection recommended. '
         'Evidence of previous plumbing leak under kitchen sink with water damage to cabinet floor and subfloor. '
         'Staining pattern suggests longstanding intermittent leak. Hot water recirculation pump non-functional. '
         'Bathroom 2 has low water pressure - may indicate galvanized supply lines in that section. '
         'Estimated repairs: Sewer line $4,000-$8,000 if root intrusion confirmed. Kitchen subfloor repair $2,000-$4,000.'),

        ('MAJOR - UNPERMITTED ADDITION', 'Converted garage/bonus room shows clear signs of non-professional construction: '
         'Drywall seams poorly taped, electrical outlets with reversed polarity, no fire separation between converted space '
         'and main structure, single-pane windows where dual-pane required. No permits found on file with City of Sunnyvale '
         'for this conversion. This may affect property value, insurance, and square footage calculations. '
         'Cost to bring to code: $15,000-$30,000.'),

        ('MAJOR - DRAINAGE', 'Negative grade at foundation on east side. Standing water evidence (mineral deposits, '
         'soil erosion) indicates water pools against foundation during rain. This is the same wall with the worst '
         'foundation cracking. French drain or regrading recommended. Estimated: $3,000-$6,000.'),

        ('MODERATE - HVAC', 'Furnace is 22 years old with visible rust on heat exchanger. Carbon monoxide reading at '
         'supply register was 12 ppm (acceptable is <9 ppm). Further evaluation by HVAC professional recommended. '
         'A/C condenser coils heavily corroded. System produced only 12°F differential (minimum acceptable: 15°F). '
         'Both units at end of life. Estimated replacement: $8,000-$12,000 for complete HVAC system.'),
    ]

    for title, desc in critical_findings:
        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(0, 6, title, ln=True)
        pdf.set_font('Helvetica', '', 8)
        pdf.multi_cell(0, 4, desc)
        pdf.ln(3)

    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'ESTIMATED TOTAL REPAIR COSTS', ln=True)
    pdf.set_font('Helvetica', '', 9)

    costs = [
        ('Foundation structural repair', '$15,000 - $45,000'),
        ('Full roof replacement', '$18,000 - $25,000'),
        ('Attic mold remediation', '$3,000 - $8,000'),
        ('Electrical panel replacement', '$2,500 - $4,000'),
        ('Electrical wiring remediation', '$5,000 - $12,000'),
        ('Sewer line repair (if confirmed)', '$4,000 - $8,000'),
        ('Kitchen subfloor repair', '$2,000 - $4,000'),
        ('Garage conversion to code', '$15,000 - $30,000'),
        ('Drainage/grading', '$3,000 - $6,000'),
        ('HVAC system replacement', '$8,000 - $12,000'),
    ]

    for item, cost in costs:
        pdf.cell(120, 5, item, ln=False)
        pdf.cell(0, 5, cost, ln=True)

    pdf.ln(3)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(120, 6, 'TOTAL ESTIMATED RANGE:', ln=False)
    pdf.cell(0, 6, '$75,500 - $154,000', ln=True)

    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(0, 6, 'Inspector: Patricia Nguyen, ASHI #189234', ln=True)
    pdf.cell(0, 6, f'Date: {(datetime.now() - timedelta(days=10)).strftime("%m/%d/%Y")}', ln=True)

    save_pdf('04_digital_inspection_nightmare.pdf', pdf.output())


# ===========================================================================
# 4. SCANNED HANDWRITTEN TDS (Image-based PDF)
# ===========================================================================
def gen_scanned_handwritten_tds():
    """Scanned paper form with handwritten entries — the #1 OCR challenge.
    ~30% of TDS uploads are partially or fully handwritten."""
    pages = []

    # Page 1: Printed form + handwritten entries
    img = Image.new('RGB', (1700, 2200), '#FFFFF5')
    draw = ImageDraw.Draw(img)
    form_font = _get_font(22, 'regular')
    hand_font = _get_font(18, 'handwritten')
    bold_font = _get_font(28, 'bold')

    # Header
    draw.text((200, 80), 'REAL ESTATE TRANSFER DISCLOSURE', fill='black', font=bold_font)
    draw.text((200, 120), 'STATEMENT', fill='black', font=bold_font)
    draw.text((200, 170), '(California Civil Code Section 1102)', fill='#444444', font=_get_font(18, 'regular'))

    # Property address - handwritten
    draw.text((200, 240), 'Property Address:', fill='black', font=form_font)
    draw.text((480, 238), '381 Tina Dr, Hollister CA 95023', fill='#1a1aCC', font=hand_font)
    draw.line((475, 262, 850, 262), fill='black', width=1)

    # Section A
    draw.text((200, 310), 'A. The subject property has the following items:', fill='black', font=form_font)

    items = [('Range', True), ('Oven', True), ('Dishwasher', True), ('Trash Compactor', False),
             ('Washer/Dryer', True), ('Rain Gutters', True), ('Burglar Alarm', False),
             ('Smoke Detector(s)', True), ('Fire Alarm', True), ('TV Antenna', False),
             ('Central Heating', True), ('Central AC', True), ('Fireplace', False),
             ('Garage: Attached', True), ('Pool', False), ('Patio/Deck', True),
             ('Water Heater: Gas', True)]

    y = 360
    for i, (item, checked) in enumerate(items):
        x = 220 + (i % 3) * 480
        if i % 3 == 0 and i > 0:
            y += 40
        draw.rectangle([x, y, x + 20, y + 20], outline='black', width=2)
        if checked:
            draw.line((x + 3, y + 3, x + 17, y + 17), fill='#1a1aCC', width=2)
            draw.line((x + 17, y + 3, x + 3, y + 17), fill='#1a1aCC', width=2)
        draw.text((x + 28, y - 2), item, fill='black', font=_get_font(16, 'regular'))

    # Section B
    y += 80
    draw.text((200, y), 'B. Are you (Seller) aware of any significant', fill='black', font=form_font)
    y += 30
    draw.text((220, y), 'defects/malfunctions in any of the following?', fill='black', font=form_font)
    y += 40

    defects = ['Interior Walls', 'Ceilings', 'Floors', 'Exterior Walls',
               'Roof(s)', 'Foundation', 'Electrical', 'Plumbing']
    for i, defect in enumerate(defects):
        x = 220 + (i % 2) * 600
        if i % 2 == 0 and i > 0:
            y += 35
        draw.text((x, y), f'[ ] Yes  [ ] No  {defect}', fill='black', font=_get_font(16, 'regular'))
        # Handwritten "No" circled
        draw.text((x + 100, y - 2), 'No', fill='#1a1aCC', font=hand_font)
        draw.ellipse([x + 95, y - 5, x + 140, y + 22], outline='#1a1aCC', width=2)

    y += 60
    draw.text((220, y), 'If yes, explain:', fill='black', font=form_font)
    draw.text((420, y - 2), 'Cosmetic cracks in walls from settling. Normal.', fill='#1a1aCC', font=hand_font)

    pages.append(img)

    # Page 2: Section C
    img2 = Image.new('RGB', (1700, 2200), '#FFFFF5')
    draw2 = ImageDraw.Draw(img2)
    draw2.text((200, 80), 'C. Are you (Seller) aware of any of the following:', fill='black', font=_get_font(24, 'bold'))

    questions = [
        ('1. Environmental hazards (asbestos, lead, mold)', 'No'),
        ('2. Features shared with adjoining landowners', 'No'),
        ('3. Encroachments, easements', 'No'),
        ('4. Room additions or structural modifications', 'Yes'),
        ('5. Additions not in compliance with building codes', 'No'),
        ('6. Fill (compacted or otherwise)', 'No'),
        ('7. Settling, slippage, sliding, soil problems', 'No'),
        ('8. Flooding, drainage, grading problems', 'Yes'),
        ('9. Major damage from fire, earthquake, floods', 'No'),
        ('10. Neighborhood noise or nuisances', 'No'),
        ('11. CC&Rs or deed restrictions', 'Yes'),
        ('12. Homeowners Association', 'Yes'),
        ('13. Any lawsuits or claims', 'No'),
    ]

    y = 140
    for q_text, answer in questions:
        draw2.text((220, y), q_text, fill='black', font=_get_font(15, 'regular'))
        y += 28
        ans_color = '#CC1a1a' if answer == 'Yes' else '#1a1aCC'
        draw2.text((260, y), answer, fill=ans_color, font=_get_font(18, 'handwritten'))
        y += 35

    pages.append(img2)

    # Page 3: Signatures
    img3 = Image.new('RGB', (1700, 2200), '#FFFFF5')
    draw3 = ImageDraw.Draw(img3)
    draw3.text((200, 80), 'D. Seller certifies the following:', fill='black', font=_get_font(24, 'bold'))
    draw3.text((220, 140), '1. Smoke detector(s) installed', fill='black', font=form_font)
    draw3.text((220, 180), '2. Water heater braced/strapped', fill='black', font=form_font)

    draw3.text((220, 280), 'Seller Signature:', fill='black', font=form_font)
    # Scrawly signature
    sig_y = 278
    for i in range(60):
        x = 460 + i * 4
        y_off = random.randint(-8, 8)
        draw3.line((x, sig_y + y_off, x + 4, sig_y + random.randint(-8, 8)), fill='#1a1aCC', width=2)

    draw3.text((220, 340), 'Date:', fill='black', font=form_font)
    draw3.text((320, 338), '01/15/2025', fill='#1a1aCC', font=hand_font)

    pages.append(img3)

    save_pdf('05_scanned_handwritten_tds.pdf', _img_to_pdf(pages))


# ===========================================================================
# 5. FADED PHOTOCOPY (low contrast, barely readable)
# ===========================================================================
def gen_faded_photocopy():
    """Bad photocopy — low contrast text on gray background. Common with older disclosures."""
    img = Image.new('RGB', (1700, 2200), '#E8E8E8')
    draw = ImageDraw.Draw(img)

    draw.text((200, 100), 'SELLER PROPERTY DISCLOSURE', fill='#B0B0B0', font=_get_font(26, 'bold'))
    draw.text((200, 160), 'Property: 999 Faded Ave, Mountain View, CA 94040', fill='#A8A8A8', font=_get_font(18))

    y = 240
    items = [
        'A. Items: Range, Dishwasher, Washer, Smoke Detector, Central Heat, Roof - Tile',
        'B. Defects: Foundation - minor settling crack (east wall)',
        '   Roof - tile, 20 years old, some cracked tiles',
        '   Plumbing - slow drain in bathroom 2',
        'C. Environmental hazards: No',
        '   Room additions without permits: No',
        '   Flooding or drainage: No',
        '   HOA: Yes - $285/month',
        'D. Smoke detectors installed. Water heater strapped.',
        '',
        'Seller: James & Patricia Morrison',
        'Date: 12/10/2024',
    ]
    for item in items:
        draw.text((220, y), item, fill='#A0A0A0', font=_get_font(16))
        y += 40

    save_pdf('06_faded_photocopy.pdf', _img_to_pdf([img], quality=40))


# ===========================================================================
# 6. CROOKED SCAN (rotated 3-5 degrees)
# ===========================================================================
def gen_crooked_scan():
    """Document scanned at an angle — common with flatbed scanners."""
    img = Image.new('RGB', (1700, 2200), 'white')
    draw = ImageDraw.Draw(img)

    draw.text((200, 100), 'HOME INSPECTION REPORT', fill='black', font=_get_font(28, 'bold'))
    draw.text((200, 160), 'Inspector: John Smith, License #CA-2019-12345', fill='black', font=_get_font(18))
    draw.text((200, 210), 'Property: 456 Crooked Lane, San Jose CA 95123', fill='black', font=_get_font(18))
    draw.text((200, 260), f'Date: {(datetime.now() - timedelta(days=7)).strftime("%B %d, %Y")}', fill='black', font=_get_font(18))

    y = 340
    findings = [
        'ROOF: Composition shingle, approx 22 years. Curling observed on south side.',
        '  Recommend: Budget for replacement in 2-3 years ($12,000-$16,000)',
        'FOUNDATION: Concrete perimeter. Hairline crack east wall, ~3ft. Monitor.',
        '  Recommend: Mark and monitor seasonally',
        'PLUMBING: Main shutoff at front. Water heater gas 40gal, 9 years old.',
        '  Kitchen faucet drips. Washer replacement needed ($100-$150)',
        'ELECTRICAL: 200 amp panel. Two outlets tested open ground in garage.',
        '  Recommend: Repair open grounds ($150-$250)',
        'HVAC: Forced air gas furnace, approx 18 years. Filter dirty at time of inspection.',
        '  A/C condenser shows corrosion. Functional but aging.',
        'EXTERIOR: Wood siding with peeling paint on north exposure.',
        '  Recommend: Scrape and repaint ($2,000-$3,500)',
        'INTERIOR: Water stain on ceiling in master bedroom. Source undetermined.',
        '  Recommend: Investigate source - may be related to roof flashing',
    ]
    for finding in findings:
        draw.text((200, y), finding, fill='black', font=_get_font(15))
        y += 38

    # Rotate 4 degrees
    rotated = img.rotate(4, expand=True, fillcolor='white')
    save_pdf('07_crooked_scan.pdf', _img_to_pdf([rotated]))


# ===========================================================================
# 7. PHONE CAMERA PHOTO of document
# ===========================================================================
def gen_phone_photo():
    """Phone camera photo of a paper document — uneven lighting, shadows, slight blur."""
    img = Image.new('RGB', (1700, 2200), '#E8E4D8')
    draw = ImageDraw.Draw(img)

    # Shadow on left side (hand holding phone)
    for x in range(350):
        alpha = int(70 * (1 - x / 350))
        for y_pos in range(0, 2200, 3):
            r, g, b = img.getpixel((x, y_pos))
            draw.point((x, y_pos), fill=(max(0, r - alpha), max(0, g - alpha), max(0, b - alpha)))

    # Document content
    draw.text((350, 120), 'TRANSFER DISCLOSURE STATEMENT', fill='#222222', font=_get_font(26, 'bold'))
    draw.text((350, 180), 'Property: 789 Phone Photo Dr, Sunnyvale CA 94087', fill='#333333', font=_get_font(18))

    y = 280
    lines = [
        'Section A: [X] Range [X] Dishwasher [X] Washer [X] Smoke Detector',
        '           [X] Garage [X] Central Heat [X] Central AC [X] Roof',
        '',
        'Section B: Are you aware of defects?',
        '  Answer: Yes - water damage in basement noted 2023',
        '  Answer: Yes - garage door opener intermittent failure',
        '',
        'Section C: Environmental hazards? No',
        '  Flooding or drainage? Yes - backyard floods in heavy rain',
        '  Room additions? Yes - converted garage to office (2019)',
        '  Permits for conversion? No',
        '  Neighborhood noise? No',
        '  HOA? Yes - $350/month',
        '',
        'Section D: Smoke detectors installed. Water heater strapped.',
        '',
        'Seller Signature: [signed]  Date: 01/22/2025',
    ]
    for line in lines:
        x_offset = random.randint(-8, 8)
        is_answer = 'Answer:' in line or 'Yes -' in line or '$350' in line
        fill_color = '#1a1aCC' if is_answer else '#222222'
        draw.text((350 + x_offset, y), line, fill=fill_color, font=_get_font(16))
        y += 38

    # Dust spots
    for _ in range(20):
        nx, ny = random.randint(0, 1700), random.randint(0, 2200)
        r = random.randint(2, 5)
        draw.ellipse([nx, ny, nx + r, ny + r], fill='#CCC8C0')

    # Slight blur (out of focus)
    img = img.filter(ImageFilter.GaussianBlur(radius=0.8))

    save_pdf('08_phone_photo.pdf', _img_to_pdf([img], quality=55))


# ===========================================================================
# 8. MIXED DIGITAL + SCANNED (cover page digital, disclosures scanned)
# ===========================================================================
def gen_mixed_digital_scanned():
    """Real-world pattern: agent creates digital cover letter, attaches scanned disclosure pages."""
    # Page 1: Digital cover
    cover = FPDF()
    cover.add_page()
    cover.set_font('Helvetica', 'B', 16)
    cover.cell(0, 10, 'SELLER DISCLOSURE PACKAGE', ln=True, align='C')
    cover.ln(5)
    cover.set_font('Helvetica', '', 11)
    cover.cell(0, 8, 'Property: 321 Mixed Ct, Mountain View, CA 94043', ln=True)
    cover.cell(0, 8, 'Prepared by: Coldwell Banker Realty', ln=True)
    cover.cell(0, 8, f'Date: {(datetime.now() - timedelta(days=20)).strftime("%B %d, %Y")}', ln=True)
    cover.ln(8)
    cover.multi_cell(0, 7, 'This package contains the following disclosure documents:\n'
                     '1. Transfer Disclosure Statement (TDS) - 3 pages\n'
                     '2. Seller Property Questionnaire (SPQ) - 2 pages\n'
                     '3. Natural Hazard Disclosure (NHD) - attached separately\n\n'
                     'Please review all documents carefully before submitting your offer.\n'
                     'Contact listing agent Lisa Park at (650) 555-0198 with questions.')
    cover.ln(5)
    cover.set_font('Helvetica', '', 8)
    cover.cell(0, 5, 'Docusign Envelope ID: C7D2F4A1-3E89-4B67-A5C3-9D1E8F2B4A67', ln=True)
    cover_bytes = cover.output()

    # Pages 2-3: Scanned handwritten disclosure
    scan1 = Image.new('RGB', (1700, 2200), '#FFFFF8')
    d1 = ImageDraw.Draw(scan1)
    d1.text((200, 80), 'TRANSFER DISCLOSURE STATEMENT', fill='black', font=_get_font(24, 'bold'))
    d1.text((200, 130), 'Property: 321 Mixed Ct, Mountain View CA 94043', fill='black', font=_get_font(18))
    d1.text((200, 200), 'Section A: Items', fill='black', font=_get_font(20, 'bold'))
    d1.text((220, 250), '[X] Range  [X] Dishwasher  [X] Smoke Detector  [X] Roof', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d1.text((220, 290), '[X] Central Heat  [X] Central AC  [X] Garage  [X] Patio', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d1.text((200, 360), 'Section B: Defects', fill='black', font=_get_font(20, 'bold'))
    d1.text((220, 410), 'Interior Walls: No', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d1.text((220, 450), 'Roof: Yes - aging shingles, some granule loss', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d1.text((220, 490), 'Foundation: No', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d1.text((220, 530), 'Electrical: No', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d1.text((220, 570), 'Plumbing: Yes - kitchen faucet drips', fill='#1a1aCC', font=_get_font(16, 'handwritten'))

    scan2 = Image.new('RGB', (1700, 2200), '#FFFFF8')
    d2 = ImageDraw.Draw(scan2)
    d2.text((200, 80), 'Section C & D', fill='black', font=_get_font(22, 'bold'))
    d2.text((220, 140), 'Environmental hazards: No', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d2.text((220, 180), 'Encroachments/easements: No', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d2.text((220, 220), 'Room additions: No', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d2.text((220, 260), 'Flooding/drainage: No', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d2.text((220, 300), 'HOA: No', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d2.text((220, 380), 'D. Smoke detector installed. Water heater strapped.', fill='#1a1aCC', font=_get_font(16, 'handwritten'))
    d2.text((220, 460), 'Seller Signature: [signed]  Date: 01/28/2025', fill='#1a1aCC', font=_get_font(16, 'handwritten'))

    # Merge digital cover + scanned pages
    scan_bytes = _img_to_pdf([scan1, scan2])
    merger = PyPDF2.PdfMerger()
    merger.append(BytesIO(cover_bytes))
    merger.append(BytesIO(scan_bytes))
    output = BytesIO()
    merger.write(output)

    save_pdf('09_mixed_digital_scanned.pdf', output.getvalue())


# ===========================================================================
# 9. ADVERSARIAL: Blank PDF
# ===========================================================================
def gen_blank_pdf():
    """Completely blank PDF — tests graceful failure."""
    pdf = FPDF()
    pdf.add_page()
    pdf.add_page()
    pdf.add_page()
    save_pdf('10_blank_3pages.pdf', pdf.output())


# ===========================================================================
# 10. ADVERSARIAL: Metadata-only PDF (DocuSign envelope with no content)
# ===========================================================================
def gen_metadata_only():
    """PDF with only DocuSign routing metadata — no actual disclosure content."""
    pdf = FPDF()
    pdf.set_font('Helvetica', '', 8)
    for i in range(3):
        pdf.add_page()
        pdf.cell(0, 10, f'Docusign Envelope ID: B6DB4E44-50E2-4439-9ED1-45DD569345A3')
        pdf.ln()
        pdf.cell(0, 10, 'Coldwell Banker Realty')
        pdf.ln()
        pdf.cell(0, 10, f'Mikala Caune 11/20/2025')
        pdf.ln()
        if i == 0:
            pdf.cell(0, 10, 'Page 1 of 3')
    save_pdf('11_metadata_only_docusign.pdf', pdf.output())


# ===========================================================================
# 11. ADVERSARIAL: Wrong document type (mortgage statement)
# ===========================================================================
def gen_wrong_doc_type():
    """Mortgage statement uploaded instead of disclosure or inspection report."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 16)
    pdf.cell(0, 10, 'MONTHLY MORTGAGE STATEMENT', ln=True, align='C')
    pdf.ln(5)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 7, 'First National Bank', ln=True)
    pdf.cell(0, 7, 'Statement Period: January 1-31, 2025', ln=True)
    pdf.cell(0, 7, 'Account Number: 1234-5678-9012', ln=True)
    pdf.cell(0, 7, 'Borrower: Michael Johnson', ln=True)
    pdf.ln(5)
    pdf.cell(0, 7, 'Property: 2847 Winfield Blvd, San Jose CA 95128', ln=True)
    pdf.ln(3)
    pdf.cell(60, 7, 'Principal Balance:', ln=False)
    pdf.cell(0, 7, '$425,000.00', ln=True)
    pdf.cell(60, 7, 'Interest Rate:', ln=False)
    pdf.cell(0, 7, '6.5% Fixed', ln=True)
    pdf.cell(60, 7, 'Monthly Payment:', ln=False)
    pdf.cell(0, 7, '$2,685.71', ln=True)
    pdf.cell(60, 7, 'Escrow:', ln=False)
    pdf.cell(0, 7, '$487.33', ln=True)
    pdf.cell(60, 7, 'Total Due:', ln=False)
    pdf.cell(0, 7, '$3,173.04', ln=True)
    pdf.ln(5)
    pdf.cell(60, 7, 'Payment Due Date:', ln=False)
    pdf.cell(0, 7, 'February 1, 2025', ln=True)
    pdf.cell(60, 7, 'Late After:', ln=False)
    pdf.cell(0, 7, 'February 16, 2025', ln=True)

    save_pdf('12_wrong_doc_mortgage.pdf', pdf.output())


# ===========================================================================
# 12. ADVERSARIAL: Corrupted PDF (partial bytes)
# ===========================================================================
def gen_corrupted_pdf():
    """PDF with valid header but corrupted content."""
    corrupted = b"%PDF-1.4\n" + b"\x00\xff\xfe" * 200 + b"\n%%EOF"
    save_pdf('13_corrupted.pdf', corrupted)


# ===========================================================================
# 13. ADVERSARIAL: Not a PDF at all (text file with .pdf extension)
# ===========================================================================
def gen_not_a_pdf():
    """Plain text file renamed to .pdf."""
    content = b"This is just a plain text file, not a PDF at all.\nSomeone renamed it to .pdf by mistake.\n"
    save_pdf('14_not_a_pdf.pdf', content)


# ===========================================================================
# 14. INSPECTION WITH EMBEDDED DAMAGE PHOTOS
# ===========================================================================
def gen_inspection_with_photos():
    """Image-based inspection report with simulated damage photos inline."""
    pages = []

    # Page 1: Cover + roof findings with photo
    p1 = Image.new('RGB', (1700, 2200), 'white')
    d1 = ImageDraw.Draw(p1)
    d1.text((400, 80), 'HOME INSPECTION REPORT', fill='black', font=_get_font(30, 'bold'))
    d1.text((200, 160), 'Inspector: Patricia Nguyen, ASHI #189234', fill='black', font=_get_font(18))
    d1.text((200, 200), 'Property: 456 Test Ave, San Jose CA 95123', fill='black', font=_get_font(18))
    d1.text((200, 240), f'Date: {(datetime.now() - timedelta(days=12)).strftime("%B %d, %Y")}', fill='black', font=_get_font(18))

    d1.text((200, 320), 'ROOF SECTION', fill='black', font=_get_font(24, 'bold'))
    d1.text((200, 360), 'Condition: DEFICIENT', fill='#CC0000', font=_get_font(20, 'bold'))
    d1.text((200, 400), 'Composition shingle roof, approximately 25 years old.', fill='black', font=_get_font(16))
    d1.text((200, 435), 'Multiple areas of curling and missing shingles observed.', fill='black', font=_get_font(16))

    # Simulated photo: water stain
    d1.text((200, 500), 'Photo 1: Water stain on master bedroom ceiling', fill='#666', font=_get_font(14))
    d1.rectangle([200, 530, 800, 930], outline='gray', width=2)
    d1.rectangle([210, 540, 790, 920], fill='#F5F0E8')
    for _ in range(50):
        x = random.randint(380, 620)
        y = random.randint(680, 820)
        r = random.randint(5, 20)
        shade = random.randint(140, 170)
        d1.ellipse([x - r, y - r, x + r, y + r],
                   fill=(shade, shade - 30, shade - 60))
    d1.text((380, 940), 'Brownish water stain ~2ft diameter', fill='#666', font=_get_font(13))

    pages.append(p1)

    # Page 2: Foundation with crack photo
    p2 = Image.new('RGB', (1700, 2200), 'white')
    d2 = ImageDraw.Draw(p2)
    d2.text((200, 80), 'FOUNDATION SECTION', fill='black', font=_get_font(24, 'bold'))
    d2.text((200, 120), 'Condition: MARGINAL', fill='#CC8800', font=_get_font(20, 'bold'))
    d2.text((200, 160), 'Concrete perimeter foundation with slab-on-grade.', fill='black', font=_get_font(16))
    d2.text((200, 195), 'Hairline crack on east wall, approximately 3 feet long.', fill='black', font=_get_font(16))
    d2.text((200, 230), 'No vertical displacement. Monitor recommended.', fill='black', font=_get_font(16))

    d2.text((200, 300), 'Photo 2: Foundation crack, east wall exterior', fill='#666', font=_get_font(14))
    d2.rectangle([200, 330, 800, 730], outline='gray', width=2)
    d2.rectangle([210, 340, 790, 720], fill='#C0C0B0')
    y_pos = 500
    for x in range(300, 700, 3):
        y_off = random.randint(-2, 2)
        y_pos += y_off
        d2.line((x, y_pos, x + 3, y_pos + random.randint(-2, 2)), fill='#333', width=1)
    d2.text((350, 740), 'Hairline crack running horizontally', fill='#666', font=_get_font(13))

    d2.text((200, 820), 'ELECTRICAL SECTION', fill='black', font=_get_font(24, 'bold'))
    d2.text((200, 860), 'Condition: SATISFACTORY', fill='#008800', font=_get_font(20, 'bold'))
    d2.text((200, 900), '200 amp panel. All circuits labeled.', fill='black', font=_get_font(16))
    d2.text((200, 935), 'Two outlets in garage tested open ground.', fill='black', font=_get_font(16))
    d2.text((200, 970), 'Recommend repair ($150-$250).', fill='black', font=_get_font(16))

    pages.append(p2)

    save_pdf('15_inspection_with_photos.pdf', _img_to_pdf(pages))


# ===========================================================================
# 15. REDACTED DISCLOSURE (sections blacked out)
# ===========================================================================
def gen_redacted_disclosure():
    """Document with blacked-out sections — sometimes seen when agents redact sensitive info."""
    img = Image.new('RGB', (1700, 2200), 'white')
    draw = ImageDraw.Draw(img)

    draw.text((200, 80), 'TRANSFER DISCLOSURE STATEMENT', fill='black', font=_get_font(24, 'bold'))
    draw.text((200, 130), 'Property: 555 Redacted Way, Palo Alto CA 94301', fill='black', font=_get_font(18))

    y = 200
    items = [
        ('Section A: Items present', False),
        ('Range, Dishwasher, Washer, Smoke Detector, Central Heat', False),
        ('Roof type: Composition, Age: 12 years', False),
        ('', False),
        ('Section B: Known defects', False),
        ('Interior Walls: No', False),
        ('Roof: No', False),
        ('Foundation: [REDACTED]', True),
        ('Electrical: No', False),
        ('Plumbing: [REDACTED]', True),
        ('', False),
        ('Section C: Awareness', False),
        ('Environmental hazards: No', False),
        ('Room additions: [REDACTED]', True),
        ('Flooding/drainage: [REDACTED]', True),
        ('HOA: Yes - $450/month', False),
        ('', False),
        ('Seller: [REDACTED]', True),
        ('Date: 01/05/2025', False),
    ]
    for text, redacted in items:
        if text:
            if redacted:
                # Black rectangle over the text
                draw.text((220, y), text.split('[')[0], fill='black', font=_get_font(16))
                draw.rectangle([220 + len(text.split('[')[0]) * 8, y - 2,
                               220 + len(text.split('[')[0]) * 8 + 200, y + 22],
                              fill='black')
            else:
                draw.text((220, y), text, fill='black', font=_get_font(16))
        y += 38

    save_pdf('16_redacted_disclosure.pdf', _img_to_pdf([img]))


# ===========================================================================
# MANIFEST
# ===========================================================================
def gen_manifest():
    """Create a manifest file describing each test PDF."""
    manifest = """# OfferWise Test Corpus Manifest
# Generated: {date}
# Total files: 16

## Clean Digital Documents (text extraction should work perfectly)
- 01_digital_tds_clean.pdf          — 4-page DocuSign-style TDS, realistic CA disclosure
- 02_digital_inspection_clean.pdf    — 15-page professional inspection report, multi-section
- 03_digital_tds_nightmare_no_disclosure.pdf — TDS where seller says "No" to everything
- 04_digital_inspection_nightmare.pdf — Inspection finding $75K-$154K in hidden problems

## Scanned/Image-Based Documents (OCR required)
- 05_scanned_handwritten_tds.pdf     — 3-page handwritten TDS on scanned paper
- 06_faded_photocopy.pdf             — Very low contrast, barely readable photocopy
- 07_crooked_scan.pdf                — Inspection report scanned at ~4 degree angle
- 08_phone_photo.pdf                 — Phone camera photo with shadows and blur
- 09_mixed_digital_scanned.pdf       — Digital cover page + scanned disclosure pages

## Inspection with Photos
- 15_inspection_with_photos.pdf      — Image-based report with embedded damage photos

## Edge Cases
- 16_redacted_disclosure.pdf         — Disclosure with blacked-out sections

## Adversarial / Invalid
- 10_blank_3pages.pdf                — Completely blank 3-page PDF
- 11_metadata_only_docusign.pdf      — DocuSign envelope metadata, no content
- 12_wrong_doc_mortgage.pdf          — Mortgage statement (wrong document type)
- 13_corrupted.pdf                   — Valid PDF header, corrupted content bytes
- 14_not_a_pdf.pdf                   — Plain text file with .pdf extension

## Test Scenarios
- Pair 01 + 02: Clean scenario (moderate issues, honest disclosure)
- Pair 03 + 04: Nightmare scenario (seller hiding $75K-$154K in problems)
- 05-09: OCR pipeline testing (various scan quality levels)
- 10-14: Adversarial input testing (graceful failure required)
- 15-16: Edge cases (photos in reports, redacted sections)
""".format(date=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

    path = os.path.join(CORPUS_DIR, 'MANIFEST.md')
    with open(path, 'w') as f:
        f.write(manifest)
    print(f"  ✅ MANIFEST.md")


# ===========================================================================
# MAIN
# ===========================================================================
if __name__ == '__main__':
    print(f"\n📄 Generating OfferWise Test Corpus → {CORPUS_DIR}/\n")

    # Core generators (fpdf2 only — always available)
    generators = [
        ('Digital TDS (clean)', gen_digital_tds_clean),
        ('Digital Inspection (15-page)', gen_digital_inspection_clean),
        ('Digital TDS (nightmare)', gen_digital_tds_nightmare),
        ('Digital Inspection (nightmare)', gen_digital_inspection_nightmare),
        ('Blank PDF', gen_blank_pdf),
        ('Metadata-only DocuSign', gen_metadata_only),
        ('Wrong Doc (Mortgage)', gen_wrong_doc_type),
        ('Corrupted PDF', gen_corrupted_pdf),
        ('Not a PDF', gen_not_a_pdf),
    ]
    
    # Image-based generators (require Pillow)
    if PILLOW_AVAILABLE:
        generators.extend([
            ('Scanned Handwritten TDS', gen_scanned_handwritten_tds),
            ('Faded Photocopy', gen_faded_photocopy),
            ('Crooked Scan', gen_crooked_scan),
            ('Phone Camera Photo', gen_phone_photo),
            ('Inspection with Photos', gen_inspection_with_photos),
            ('Redacted Disclosure', gen_redacted_disclosure),
        ])
    
    # Mixed PDF (requires Pillow + PyPDF2)
    if PILLOW_AVAILABLE and PYPDF2_AVAILABLE:
        generators.append(('Mixed Digital + Scanned', gen_mixed_digital_scanned))
    
    generators.append(('Manifest', gen_manifest))

    for name, gen_func in generators:
        try:
            gen_func()
        except Exception as e:
            print(f"  ❌ {name}: {e}")

    print(f"\n✅ Corpus complete: {len(os.listdir(CORPUS_DIR))} files in test_corpus/")
    total_size = sum(os.path.getsize(os.path.join(CORPUS_DIR, f)) for f in os.listdir(CORPUS_DIR))
    print(f"   Total size: {total_size / 1024:.0f} KB\n")
