"""v5_75_65_full_schema

Revision ID: 1f857ccea478
Revises: 
Create Date: 2026-03-17 22:22:05.737802
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1f857ccea478'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('actual_behavior', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version_reported', sa.String(length=20), nullable=True),
    sa.Column('version_fixed', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('fixed_at', sa.DateTime(), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('fix_notes', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_suggested_fix', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=20), nullable=True),
    sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_fix_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_state', sa.String(length=2), nullable=True),
    sa.Column('license_verified', sa.Boolean(), nullable=True),
    sa.Column('trades', sa.String(length=500), nullable=True),
    sa.Column('trade_notes', sa.Text(), nullable=True),
    sa.Column('service_zips', sa.String(length=1000), nullable=True),
    sa.Column('service_cities', sa.String(length=500), nullable=True),
    sa.Column('service_radius_miles', sa.Integer(), nullable=True),
    sa.Column('accepts_leads', sa.Boolean(), nullable=True),
    sa.Column('max_leads_month', sa.Integer(), nullable=True),
    sa.Column('leads_sent_month', sa.Integer(), nullable=True),
    sa.Column('leads_sent_total', sa.Integer(), nullable=True),
    sa.Column('jobs_closed', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_id', sa.String(length=100), nullable=True),
    sa.Column('plan_activated_at', sa.DateTime(), nullable=True),
    sa.Column('monthly_lead_limit', sa.Integer(), nullable=True),
    sa.Column('avg_job_size', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('unavailable_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_accepts_leads'), 'contractors', ['accepts_leads'], unique=False)
    op.create_index(op.f('ix_contractors_available'), 'contractors', ['available'], unique=False)
    op.create_index(op.f('ix_contractors_created_at'), 'contractors', ['created_at'], unique=False)
    op.create_index(op.f('ix_contractors_email'), 'contractors', ['email'], unique=False)
    op.create_index(op.f('ix_contractors_status'), 'contractors', ['status'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('resend_id', sa.String(length=100), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('link_url', sa.String(length=1000), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_event_type'), 'email_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_events_resend_id'), 'email_events', ['resend_id'], unique=False)
    op.create_index(op.f('ix_email_events_to_email'), 'email_events', ['to_email'], unique=False)
    op.create_index(op.f('ix_email_events_ts'), 'email_events', ['ts'], unique=False)
    op.create_table('email_registry',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_signup_date', sa.DateTime(), nullable=False),
    sa.Column('has_received_free_credit', sa.Boolean(), nullable=False),
    sa.Column('free_credit_given_at', sa.DateTime(), nullable=True),
    sa.Column('times_deleted', sa.Integer(), nullable=False),
    sa.Column('last_deleted_at', sa.DateTime(), nullable=True),
    sa.Column('saved_credits', sa.Integer(), nullable=False),
    sa.Column('credits_saved_at', sa.DateTime(), nullable=True),
    sa.Column('is_flagged_abuse', sa.Boolean(), nullable=False),
    sa.Column('abuse_notes', sa.Text(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('gtm_ad_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'date', name='uq_channel_date')
    )
    op.create_index(op.f('ix_gtm_ad_performance_channel'), 'gtm_ad_performance', ['channel'], unique=False)
    op.create_index(op.f('ix_gtm_ad_performance_date'), 'gtm_ad_performance', ['date'], unique=False)
    op.create_table('gtm_scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('posts_scanned', sa.Integer(), nullable=True),
    sa.Column('posts_filtered', sa.Integer(), nullable=True),
    sa.Column('posts_scored', sa.Integer(), nullable=True),
    sa.Column('drafts_created', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtm_scan_runs_started_at'), 'gtm_scan_runs', ['started_at'], unique=False)
    op.create_table('gtm_scanned_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('selftext', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('reddit_score', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('keyword_score', sa.Integer(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('ai_topics', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtm_scanned_threads_platform'), 'gtm_scanned_threads', ['platform'], unique=False)
    op.create_index(op.f('ix_gtm_scanned_threads_reddit_id'), 'gtm_scanned_threads', ['reddit_id'], unique=True)
    op.create_index(op.f('ix_gtm_scanned_threads_scanned_at'), 'gtm_scanned_threads', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_gtm_scanned_threads_status'), 'gtm_scanned_threads', ['status'], unique=False)
    op.create_index(op.f('ix_gtm_scanned_threads_subreddit'), 'gtm_scanned_threads', ['subreddit'], unique=False)
    op.create_table('gtm_subreddit_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('edited_body', sa.Text(), nullable=True),
    sa.Column('pillar', sa.String(length=50), nullable=False),
    sa.Column('pillar_label', sa.String(length=100), nullable=True),
    sa.Column('flair', sa.String(length=50), nullable=True),
    sa.Column('data_summary', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('skip_reason', sa.String(length=200), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('posted_url', sa.String(length=500), nullable=True),
    sa.Column('topic_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtm_subreddit_posts_scheduled_date'), 'gtm_subreddit_posts', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_gtm_subreddit_posts_status'), 'gtm_subreddit_posts', ['status'], unique=False)
    op.create_index(op.f('ix_gtm_subreddit_posts_topic_key'), 'gtm_subreddit_posts', ['topic_key'], unique=False)
    op.create_table('gtm_target_subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'platform', name='uq_target_name_platform')
    )
    op.create_index(op.f('ix_gtm_target_subreddits_enabled'), 'gtm_target_subreddits', ['enabled'], unique=False)
    op.create_index(op.f('ix_gtm_target_subreddits_platform'), 'gtm_target_subreddits', ['platform'], unique=False)
    op.create_table('infra_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('logo_emoji', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_links_email'), 'magic_links', ['email'], unique=False)
    op.create_index(op.f('ix_magic_links_token'), 'magic_links', ['token'], unique=True)
    op.create_table('repair_cost_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cost_low', sa.Integer(), nullable=False),
    sa.Column('cost_high', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'severity', name='uq_category_severity')
    )
    op.create_table('repair_cost_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_prefix', sa.String(length=3), nullable=False),
    sa.Column('metro_name', sa.String(length=100), nullable=False),
    sa.Column('cost_multiplier', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_cost_zones_zip_prefix'), 'repair_cost_zones', ['zip_prefix'], unique=True)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('turk_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turk_id', sa.String(length=100), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('session_token', sa.String(length=50), nullable=True),
    sa.Column('completion_code', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('uploaded_disclosure', sa.Boolean(), nullable=True),
    sa.Column('uploaded_inspection', sa.Boolean(), nullable=True),
    sa.Column('started_analysis', sa.Boolean(), nullable=True),
    sa.Column('viewed_results', sa.Boolean(), nullable=True),
    sa.Column('viewed_risk_dna', sa.Boolean(), nullable=True),
    sa.Column('viewed_transparency', sa.Boolean(), nullable=True),
    sa.Column('viewed_decision_path', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('would_pay', sa.Boolean(), nullable=True),
    sa.Column('confusion_points', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turk_sessions_session_token'), 'turk_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_turk_sessions_task_id'), 'turk_sessions', ['task_id'], unique=False)
    op.create_index(op.f('ix_turk_sessions_turk_id'), 'turk_sessions', ['turk_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('apple_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('analysis_credits', sa.Integer(), nullable=True),
    sa.Column('total_credits_purchased', sa.Integer(), nullable=True),
    sa.Column('analyses_completed', sa.Integer(), nullable=True),
    sa.Column('max_budget', sa.Integer(), nullable=True),
    sa.Column('repair_tolerance', sa.String(length=50), nullable=True),
    sa.Column('biggest_regret', sa.Text(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('referral_code', sa.String(length=50), nullable=True),
    sa.Column('referred_by_code', sa.String(length=50), nullable=True),
    sa.Column('referred_by_user_id', sa.Integer(), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=True),
    sa.Column('referral_tier', sa.Integer(), nullable=True),
    sa.Column('referral_credits_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('terms_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by_code'), 'users', ['referred_by_code'], unique=False)
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('had_result', sa.Boolean(), nullable=True),
    sa.Column('result_score', sa.Integer(), nullable=True),
    sa.Column('result_address', sa.String(length=500), nullable=True),
    sa.Column('result_grade', sa.String(length=5), nullable=True),
    sa.Column('result_exposure', sa.Integer(), nullable=True),
    sa.Column('result_zip', sa.String(length=10), nullable=True),
    sa.Column('result_city', sa.String(length=100), nullable=True),
    sa.Column('result_state', sa.String(length=2), nullable=True),
    sa.Column('drip_step', sa.Integer(), nullable=True),
    sa.Column('drip_last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('drip_completed', sa.Boolean(), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=True),
    sa.Column('email_unsubscribed', sa.Boolean(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_created_at'), 'waitlist', ['created_at'], unique=False)
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=False)
    op.create_index(op.f('ix_waitlist_result_zip'), 'waitlist', ['result_zip'], unique=False)
    op.create_index(op.f('ix_waitlist_unsubscribe_token'), 'waitlist', ['unsubscribe_token'], unique=True)
    op.create_table('ai_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('context_note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_logs_endpoint'), 'ai_call_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_ts'), 'ai_call_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_user_id'), 'ai_call_logs', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=True),
    sa.Column('key_prefix', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('calls_total', sa.Integer(), nullable=True),
    sa.Column('calls_month', sa.Integer(), nullable=True),
    sa.Column('monthly_limit', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('price_per_call', sa.Float(), nullable=True),
    sa.Column('monthly_fee', sa.Float(), nullable=True),
    sa.Column('revenue_month', sa.Float(), nullable=True),
    sa.Column('revenue_total', sa.Float(), nullable=True),
    sa.Column('invoice_day', sa.Integer(), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('contractor_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_phone', sa.String(length=50), nullable=True),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('property_zip', sa.String(length=10), nullable=True),
    sa.Column('repair_system', sa.String(length=100), nullable=True),
    sa.Column('trade_needed', sa.String(length=100), nullable=True),
    sa.Column('cost_estimate', sa.String(length=100), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('contact_timing', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=True),
    sa.Column('assigned_contractor_id', sa.Integer(), nullable=True),
    sa.Column('sent_to_contractor_at', sa.DateTime(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('job_closed_at', sa.DateTime(), nullable=True),
    sa.Column('job_value', sa.Float(), nullable=True),
    sa.Column('referral_fee_pct', sa.Float(), nullable=True),
    sa.Column('referral_fee_due', sa.Float(), nullable=True),
    sa.Column('referral_paid', sa.Boolean(), nullable=True),
    sa.Column('referral_paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_leads_assigned_contractor_id'), 'contractor_leads', ['assigned_contractor_id'], unique=False)
    op.create_index(op.f('ix_contractor_leads_created_at'), 'contractor_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_contractor_leads_status'), 'contractor_leads', ['status'], unique=False)
    op.create_index(op.f('ix_contractor_leads_user_email'), 'contractor_leads', ['user_email'], unique=False)
    op.create_index(op.f('ix_contractor_leads_user_id'), 'contractor_leads', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_payment_intent_id'), 'credit_transactions', ['payment_intent_id'], unique=True)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('email_send_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('resend_id', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_send_log_email_type'), 'email_send_log', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_send_log_to_email'), 'email_send_log', ['to_email'], unique=False)
    op.create_index(op.f('ix_email_send_log_ts'), 'email_send_log', ['ts'], unique=False)
    op.create_index(op.f('ix_email_send_log_user_id'), 'email_send_log', ['user_id'], unique=False)
    op.create_table('exit_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('exit_reason', sa.String(length=100), nullable=True),
    sa.Column('exit_reason_other', sa.Text(), nullable=True),
    sa.Column('exit_page', sa.String(length=100), nullable=True),
    sa.Column('would_return', sa.Boolean(), nullable=True),
    sa.Column('what_would_help', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_surveys_session_id'), 'exit_surveys', ['session_id'], unique=False)
    op.create_index(op.f('ix_exit_surveys_user_id'), 'exit_surveys', ['user_id'], unique=False)
    op.create_table('gtm_funnel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtm_funnel_events_created_at'), 'gtm_funnel_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_gtm_funnel_events_source'), 'gtm_funnel_events', ['source'], unique=False)
    op.create_index(op.f('ix_gtm_funnel_events_stage'), 'gtm_funnel_events', ['stage'], unique=False)
    op.create_table('gtm_reddit_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('mention_type', sa.String(length=30), nullable=True),
    sa.Column('edited_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('skip_reason', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('posted_url', sa.String(length=500), nullable=True),
    sa.Column('reddit_comment_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['gtm_scanned_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtm_reddit_drafts_created_at'), 'gtm_reddit_drafts', ['created_at'], unique=False)
    op.create_index(op.f('ix_gtm_reddit_drafts_status'), 'gtm_reddit_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_gtm_reddit_drafts_thread_id'), 'gtm_reddit_drafts', ['thread_id'], unique=False)
    op.create_table('infra_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('invoice_ref', sa.String(length=100), nullable=True),
    sa.Column('pdf_data', sa.Text(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('pdf_mime', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['infra_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'period_start', name='uq_vendor_period')
    )
    op.create_index(op.f('ix_infra_invoices_vendor_id'), 'infra_invoices', ['vendor_id'], unique=False)
    op.create_table('inspectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_state', sa.String(length=2), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('service_areas', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=True),
    sa.Column('monthly_used', sa.Integer(), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(), nullable=True),
    sa.Column('total_reports', sa.Integer(), nullable=True),
    sa.Column('total_buyers_converted', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectors_user_id'), 'inspectors', ['user_id'], unique=True)
    op.create_table('listing_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_hash', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_hash', name='uq_user_listing')
    )
    op.create_index(op.f('ix_listing_preferences_user_id'), 'listing_preferences', ['user_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('median_price', sa.Integer(), nullable=True),
    sa.Column('active_inventory', sa.Integer(), nullable=True),
    sa.Column('avg_dom', sa.Integer(), nullable=True),
    sa.Column('new_listings_count', sa.Integer(), nullable=True),
    sa.Column('median_price_delta_pct', sa.Float(), nullable=True),
    sa.Column('inventory_delta', sa.Integer(), nullable=True),
    sa.Column('avg_dom_delta', sa.Integer(), nullable=True),
    sa.Column('matched_listings_json', sa.Text(), nullable=True),
    sa.Column('top_match_score', sa.Integer(), nullable=True),
    sa.Column('top_match_address', sa.String(length=300), nullable=True),
    sa.Column('new_comps_json', sa.Text(), nullable=True),
    sa.Column('new_comps_count', sa.Integer(), nullable=True),
    sa.Column('alerts_generated', sa.Integer(), nullable=True),
    sa.Column('alert_email_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'zip_code', 'snapshot_date', name='uq_user_zip_date')
    )
    op.create_index(op.f('ix_market_snapshots_snapshot_date'), 'market_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_market_snapshots_user_id'), 'market_snapshots', ['user_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_zip_code'), 'market_snapshots', ['zip_code'], unique=False)
    op.create_table('pmf_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('disappointment', sa.String(length=50), nullable=True),
    sa.Column('main_benefit', sa.Text(), nullable=True),
    sa.Column('improvement', sa.Text(), nullable=True),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('recommend_to', sa.Text(), nullable=True),
    sa.Column('analyses_at_survey', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pmf_surveys_email'), 'pmf_surveys', ['email'], unique=False)
    op.create_index(op.f('ix_pmf_surveys_user_id'), 'pmf_surveys', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_user_id'), 'properties', ['user_id'], unique=False)
    op.create_table('quick_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('reaction', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('page', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_feedback_user_id'), 'quick_feedback', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=False),
    sa.Column('signup_date', sa.DateTime(), nullable=True),
    sa.Column('credits_awarded', sa.Boolean(), nullable=True),
    sa.Column('first_analysis_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referee_id'), 'referrals', ['referee_id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('scout_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('zip_codes', sa.Text(), nullable=False),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=False),
    sa.Column('bedrooms_min', sa.Integer(), nullable=True),
    sa.Column('bathrooms_min', sa.Integer(), nullable=True),
    sa.Column('sqft_min', sa.Integer(), nullable=True),
    sa.Column('property_types', sa.Text(), nullable=True),
    sa.Column('alert_frequency', sa.String(length=20), nullable=True),
    sa.Column('auto_analyze', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scout_profiles_user_id'), 'scout_profiles', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month_start', sa.DateTime(), nullable=False),
    sa.Column('properties_analyzed', sa.Integer(), nullable=True),
    sa.Column('last_analysis', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month_start', name='unique_user_month')
    )
    op.create_index(op.f('ix_usage_records_month_start'), 'usage_records', ['month_start'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('offer_score', sa.Float(), nullable=True),
    sa.Column('risk_tier', sa.String(length=50), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('buyer_profile_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_property_id'), 'analyses', ['property_id'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_table('contractor_lead_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('passed_at', sa.DateTime(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('job_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['contractor_leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'contractor_id', name='unique_lead_contractor')
    )
    op.create_index(op.f('ix_contractor_lead_claims_contractor_id'), 'contractor_lead_claims', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contractor_lead_claims_created_at'), 'contractor_lead_claims', ['created_at'], unique=False)
    op.create_index(op.f('ix_contractor_lead_claims_lead_id'), 'contractor_lead_claims', ['lead_id'], unique=False)
    op.create_index(op.f('ix_contractor_lead_claims_status'), 'contractor_lead_claims', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_property_id'), 'documents', ['property_id'], unique=False)
    op.create_table('inspector_referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('referrer_id', sa.Integer(), nullable=True),
    sa.Column('referred_email', sa.String(length=255), nullable=True),
    sa.Column('referred_name', sa.String(length=255), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('invite_sent_at', sa.DateTime(), nullable=True),
    sa.Column('signed_up_at', sa.DateTime(), nullable=True),
    sa.Column('bonus_granted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['referrer_id'], ['inspectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspector_referrals_invite_token'), 'inspector_referrals', ['invite_token'], unique=True)
    op.create_index(op.f('ix_inspector_referrals_referrer_id'), 'inspector_referrals', ['referrer_id'], unique=False)
    op.create_table('inspector_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('inspector_user_id', sa.Integer(), nullable=False),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('property_price', sa.Float(), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('inspection_text', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=32), nullable=True),
    sa.Column('inspector_name_on_report', sa.String(length=255), nullable=True),
    sa.Column('inspector_biz_on_report', sa.String(length=255), nullable=True),
    sa.Column('buyer_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_registered', sa.Boolean(), nullable=True),
    sa.Column('buyer_converted', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['inspectors.id'], ),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspector_reports_created_at'), 'inspector_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspector_reports_inspector_id'), 'inspector_reports', ['inspector_id'], unique=False)
    op.create_index(op.f('ix_inspector_reports_share_token'), 'inspector_reports', ['share_token'], unique=True)
    op.create_table('referral_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('credits_awarded', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_rewards_user_id'), 'referral_rewards', ['user_id'], unique=False)
    op.create_table('repair_cost_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('metro_name', sa.String(length=100), nullable=True),
    sa.Column('cost_multiplier', sa.Float(), nullable=True),
    sa.Column('total_low', sa.Integer(), nullable=True),
    sa.Column('total_high', sa.Integer(), nullable=True),
    sa.Column('breakdown_json', sa.Text(), nullable=True),
    sa.Column('property_year_built', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scout_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('listing_url', sa.String(length=1000), nullable=True),
    sa.Column('listed_date', sa.DateTime(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('price_per_sqft', sa.Float(), nullable=True),
    sa.Column('listing_status', sa.String(length=50), nullable=True),
    sa.Column('listing_source', sa.String(length=50), nullable=True),
    sa.Column('scout_score', sa.Float(), nullable=True),
    sa.Column('value_score', sa.Float(), nullable=True),
    sa.Column('location_score', sa.Float(), nullable=True),
    sa.Column('condition_score', sa.Float(), nullable=True),
    sa.Column('opportunity_signal', sa.String(length=100), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('avm_estimate', sa.Integer(), nullable=True),
    sa.Column('avm_vs_price_pct', sa.Float(), nullable=True),
    sa.Column('zip_median_price', sa.Integer(), nullable=True),
    sa.Column('zip_avg_dom', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.Column('listing_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['scout_profiles.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scout_matches_listing_hash'), 'scout_matches', ['listing_hash'], unique=False)
    op.create_index(op.f('ix_scout_matches_profile_id'), 'scout_matches', ['profile_id'], unique=False)
    op.create_index(op.f('ix_scout_matches_user_id'), 'scout_matches', ['user_id'], unique=False)
    op.create_index(op.f('ix_scout_matches_zip_code'), 'scout_matches', ['zip_code'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('sharer_name', sa.String(length=100), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('personal_note', sa.String(length=280), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('first_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('reactions_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.create_index(op.f('ix_share_links_user_id'), 'share_links', ['user_id'], unique=False)
    op.create_table('support_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(length=1000), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('full_result_json', sa.Text(), nullable=False),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_shares_created_at'), 'support_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_shares_user_id'), 'support_shares', ['user_id'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property1_address', sa.String(length=500), nullable=True),
    sa.Column('property1_listing_url', sa.String(length=1000), nullable=True),
    sa.Column('property1_price', sa.Integer(), nullable=True),
    sa.Column('property1_analysis_id', sa.Integer(), nullable=True),
    sa.Column('property2_address', sa.String(length=500), nullable=True),
    sa.Column('property2_listing_url', sa.String(length=1000), nullable=True),
    sa.Column('property2_price', sa.Integer(), nullable=True),
    sa.Column('property2_analysis_id', sa.Integer(), nullable=True),
    sa.Column('property3_address', sa.String(length=500), nullable=True),
    sa.Column('property3_listing_url', sa.String(length=1000), nullable=True),
    sa.Column('property3_price', sa.Integer(), nullable=True),
    sa.Column('property3_analysis_id', sa.Integer(), nullable=True),
    sa.Column('comparison_data', sa.JSON(), nullable=True),
    sa.Column('winner_property', sa.Integer(), nullable=True),
    sa.Column('rankings', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property1_analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['property2_analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['property3_analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_user_id'), 'comparisons', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consent_text_hash', sa.String(length=64), nullable=True),
    sa.Column('consented_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_comparisons_user_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_support_shares_user_id'), table_name='support_shares')
    op.drop_index(op.f('ix_support_shares_created_at'), table_name='support_shares')
    op.drop_table('support_shares')
    op.drop_index(op.f('ix_share_links_user_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_scout_matches_zip_code'), table_name='scout_matches')
    op.drop_index(op.f('ix_scout_matches_user_id'), table_name='scout_matches')
    op.drop_index(op.f('ix_scout_matches_profile_id'), table_name='scout_matches')
    op.drop_index(op.f('ix_scout_matches_listing_hash'), table_name='scout_matches')
    op.drop_table('scout_matches')
    op.drop_table('repair_cost_logs')
    op.drop_index(op.f('ix_referral_rewards_user_id'), table_name='referral_rewards')
    op.drop_table('referral_rewards')
    op.drop_index(op.f('ix_inspector_reports_share_token'), table_name='inspector_reports')
    op.drop_index(op.f('ix_inspector_reports_inspector_id'), table_name='inspector_reports')
    op.drop_index(op.f('ix_inspector_reports_created_at'), table_name='inspector_reports')
    op.drop_table('inspector_reports')
    op.drop_index(op.f('ix_inspector_referrals_referrer_id'), table_name='inspector_referrals')
    op.drop_index(op.f('ix_inspector_referrals_invite_token'), table_name='inspector_referrals')
    op.drop_table('inspector_referrals')
    op.drop_index(op.f('ix_documents_property_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_contractor_lead_claims_status'), table_name='contractor_lead_claims')
    op.drop_index(op.f('ix_contractor_lead_claims_lead_id'), table_name='contractor_lead_claims')
    op.drop_index(op.f('ix_contractor_lead_claims_created_at'), table_name='contractor_lead_claims')
    op.drop_index(op.f('ix_contractor_lead_claims_contractor_id'), table_name='contractor_lead_claims')
    op.drop_table('contractor_lead_claims')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_property_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_month_start'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_scout_profiles_user_id'), table_name='scout_profiles')
    op.drop_table('scout_profiles')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referee_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_quick_feedback_user_id'), table_name='quick_feedback')
    op.drop_table('quick_feedback')
    op.drop_index(op.f('ix_properties_user_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_pmf_surveys_user_id'), table_name='pmf_surveys')
    op.drop_index(op.f('ix_pmf_surveys_email'), table_name='pmf_surveys')
    op.drop_table('pmf_surveys')
    op.drop_index(op.f('ix_market_snapshots_zip_code'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_user_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_snapshot_date'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_listing_preferences_user_id'), table_name='listing_preferences')
    op.drop_table('listing_preferences')
    op.drop_index(op.f('ix_inspectors_user_id'), table_name='inspectors')
    op.drop_table('inspectors')
    op.drop_index(op.f('ix_infra_invoices_vendor_id'), table_name='infra_invoices')
    op.drop_table('infra_invoices')
    op.drop_index(op.f('ix_gtm_reddit_drafts_thread_id'), table_name='gtm_reddit_drafts')
    op.drop_index(op.f('ix_gtm_reddit_drafts_status'), table_name='gtm_reddit_drafts')
    op.drop_index(op.f('ix_gtm_reddit_drafts_created_at'), table_name='gtm_reddit_drafts')
    op.drop_table('gtm_reddit_drafts')
    op.drop_index(op.f('ix_gtm_funnel_events_stage'), table_name='gtm_funnel_events')
    op.drop_index(op.f('ix_gtm_funnel_events_source'), table_name='gtm_funnel_events')
    op.drop_index(op.f('ix_gtm_funnel_events_created_at'), table_name='gtm_funnel_events')
    op.drop_table('gtm_funnel_events')
    op.drop_index(op.f('ix_exit_surveys_user_id'), table_name='exit_surveys')
    op.drop_index(op.f('ix_exit_surveys_session_id'), table_name='exit_surveys')
    op.drop_table('exit_surveys')
    op.drop_index(op.f('ix_email_send_log_user_id'), table_name='email_send_log')
    op.drop_index(op.f('ix_email_send_log_ts'), table_name='email_send_log')
    op.drop_index(op.f('ix_email_send_log_to_email'), table_name='email_send_log')
    op.drop_index(op.f('ix_email_send_log_email_type'), table_name='email_send_log')
    op.drop_table('email_send_log')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_payment_intent_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_contractor_leads_user_id'), table_name='contractor_leads')
    op.drop_index(op.f('ix_contractor_leads_user_email'), table_name='contractor_leads')
    op.drop_index(op.f('ix_contractor_leads_status'), table_name='contractor_leads')
    op.drop_index(op.f('ix_contractor_leads_created_at'), table_name='contractor_leads')
    op.drop_index(op.f('ix_contractor_leads_assigned_contractor_id'), table_name='contractor_leads')
    op.drop_table('contractor_leads')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_call_logs_user_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_ts'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_endpoint'), table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    op.drop_index(op.f('ix_waitlist_unsubscribe_token'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_result_zip'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_created_at'), table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index(op.f('ix_users_referred_by_code'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_turk_sessions_turk_id'), table_name='turk_sessions')
    op.drop_index(op.f('ix_turk_sessions_task_id'), table_name='turk_sessions')
    op.drop_index(op.f('ix_turk_sessions_session_token'), table_name='turk_sessions')
    op.drop_table('turk_sessions')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_repair_cost_zones_zip_prefix'), table_name='repair_cost_zones')
    op.drop_table('repair_cost_zones')
    op.drop_table('repair_cost_baselines')
    op.drop_index(op.f('ix_magic_links_token'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_email'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_table('infra_vendors')
    op.drop_index(op.f('ix_gtm_target_subreddits_platform'), table_name='gtm_target_subreddits')
    op.drop_index(op.f('ix_gtm_target_subreddits_enabled'), table_name='gtm_target_subreddits')
    op.drop_table('gtm_target_subreddits')
    op.drop_index(op.f('ix_gtm_subreddit_posts_topic_key'), table_name='gtm_subreddit_posts')
    op.drop_index(op.f('ix_gtm_subreddit_posts_status'), table_name='gtm_subreddit_posts')
    op.drop_index(op.f('ix_gtm_subreddit_posts_scheduled_date'), table_name='gtm_subreddit_posts')
    op.drop_table('gtm_subreddit_posts')
    op.drop_index(op.f('ix_gtm_scanned_threads_subreddit'), table_name='gtm_scanned_threads')
    op.drop_index(op.f('ix_gtm_scanned_threads_status'), table_name='gtm_scanned_threads')
    op.drop_index(op.f('ix_gtm_scanned_threads_scanned_at'), table_name='gtm_scanned_threads')
    op.drop_index(op.f('ix_gtm_scanned_threads_reddit_id'), table_name='gtm_scanned_threads')
    op.drop_index(op.f('ix_gtm_scanned_threads_platform'), table_name='gtm_scanned_threads')
    op.drop_table('gtm_scanned_threads')
    op.drop_index(op.f('ix_gtm_scan_runs_started_at'), table_name='gtm_scan_runs')
    op.drop_table('gtm_scan_runs')
    op.drop_index(op.f('ix_gtm_ad_performance_date'), table_name='gtm_ad_performance')
    op.drop_index(op.f('ix_gtm_ad_performance_channel'), table_name='gtm_ad_performance')
    op.drop_table('gtm_ad_performance')
    op.drop_table('email_registry')
    op.drop_index(op.f('ix_email_events_ts'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_to_email'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_resend_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_event_type'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_contractors_status'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_email'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_created_at'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_available'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_accepts_leads'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_table('bugs')
    # ### end Alembic commands ###
